name = "osrs-flip-worker2"
main = "src/index.js"
compatibility_date = "2025-08-17"
compatibility_flags = ["nodejs_compat"]

-------------------------------,
Production Environment,
-------------------------------,
[env.production]
name = "osrs-flip-prod"
routes = [
  { pattern = "osrsfliptips.com/", zone_name = "osrsfliptips.com" }
]

-------------------------------,
Staging Environment,
-------------------------------,
[env.staging]
name = "osrs-flip-staging"
routes = [
  { pattern = "osrsfliptips.com/v2/", zone_name = "osrsfliptips.com" }
]