name = "osrs-flip-worker2"
main = "src/index.js"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

# --- STAGING (/v2/*) ---
[env.staging]
name = "osrs-flip-staging"
routes = [
  { pattern = "osrsfliptips.com/v2/*", zone_name = "osrsfliptips.com" }
]

# --- PRODUCTION (/*) ---
[env.production]
name = "osrs-flip-prod"
routes = [
  { pattern = "osrsfliptips.com/*", zone_name = "osrsfliptips.com" }
]
