name: Deploy FlipTips via Wrangler

on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if needed)
        run: |
          if [ -f package.json ]; then
            npm ci || npm i
          fi

      - name: Deploy with Wrangler (branch decides env)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            if [ "${{ gith]()


echo "// deploy fix $(date)" >> poke3.js
git add poke3.js
git commit -m "ci: trigger deploy with fixed workflow"
git push

git checkout staging

mkdir -p .github/workflows
cat > .github/workflows/deploy.yml <<'YAML'
name: Deploy FlipTips via Wrangler

on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if needed)
        run: |
          if [ -f package.json ]; then
            npm ci || npm i
          fi

      - name: Deploy with Wrangler (branch decides env)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            if [ "${{ github.ref_name }}" = "main" ]; then
              deploy --env production
            else
              deploy --env staging
            fi
