name: Deploy FlipTips via Wrangler

on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if needed)
        run: |
          if [ -f package.json ]; then
            npm ci || npm i
          fi

      - name: Deploy to production
        if: github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
  

               with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --env production

        - name: Deploy to staging
        if: github.ref_name != 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
                   command: deploy --env staging
