name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DEPLOY to confirm deployment to production"
        required: true
        default: ""

jobs:
  deploy:
    if: ${{ github.event.inputs.confirm == 'DEPLOY' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g wrangler
      - run: wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
